import Head from 'next/head'
import Image from 'next/image'
import {InputText} from 'primereact/inputtext'
import { Button } from 'primereact/button';

import "primereact/resources/themes/lara-light-indigo/theme.css";
import "primereact/resources/primereact.min.css";
import "primeicons/primeicons.css";


import Imagez from "../public/unnamed.png"
import { useState } from 'react';
import QRCode from 'react-qr-code';


export default function Home() {
  const [url, setUrl] = useState("")
  const [hide, setHide] = useState(false)

  const generateQRCode = () => {
    setHide(true)
  }
  return (
    <div className=''>
      <Head>
        <link rel="stylesheet" href="https://unpkg.com/primeflex@3.1.2/primeflex.css" />

        <title>QR Code Generator </title>
        <meta name="description" content="Generated by Tolga BAYRAK" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className=''>
        <div className="grid">
          <div className="col-12 bg-gray-100 h-min-full">
            <div className="grid">
              <div className="col-12 bg-green-300">
                <h5 className='text-center text-white text-xl m-3'>Generate QR Code</h5>
              
              </div>
              <div className='m-auto border-round-xl  '>
              <Image
                  className='p-3 '
                  src={Imagez}
                  alt="Picture of the author"
                   width={200} 
                   height={200}  
                />
              </div>

            </div>
            <h2 className='text-center'>QR Code Generator</h2>
            <p className='text-center w-5 m-auto text-sm'>
            Well, the QR – 
            which stands for “quick response” – 
            code is basically a barcode on steroids. While the barcode holds information 
            horizontally, the QR code does so both horizontally and vertically. 
            This enables the QR code to hold over a hundred times more information..
            </p>
            <p className='text-center pt-4'>
              Enter your URL below yo generate a QR Code and download the image.
            </p>

              
             <InputText onChange={(e)=> setUrl(e.target.value)}  id="url" className='w-2 flex m-auto ' placeholder="Enter your URL"/>
             <Button onClick={generateQRCode} label="Generate QR Code" className="p-button-outlined p-button-success mt-3 flex w-2 m-auto" />
             <div className='text-center mt-5'>
              
              {
                hide &&
                <div>
                  <p>Your QR Code :</p>
                  <QRCode
                  title="QR Code"
                  value={url}
                  bgColor="white"
                  size={200}
                  />

                </div>
     
              }
         
             </div>

          </div>
          

    
      
        </div>
        
      </main>
      <footer className='bg-gray-100 p-2'>
        <p className='text-center'>created Tolga BAYRAK @2022</p>
        </footer>

 


    </div>
  )
}
