import Head from 'next/head'
import Image from 'next/image'
import {InputText} from 'primereact/inputtext'

import "primereact/resources/themes/lara-light-indigo/theme.css";  
import "primereact/resources/primereact.min.css";                  
import "primeicons/primeicons.css";
      

export default function Home() {
  return (
    <div>
      <Head>
      <link rel="stylesheet" href="https://unpkg.com/primeflex@3.1.2/primeflex.css" />

        <title>Generate Qr-Code </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
      <InputText />
      </main>

      <footer>
 
      </footer>
      <script src="https://unpkg.com/primereact/primereact.all.min.js"></script>

    </div>
  )
}
